import type {Analysis,GlobalModelDashboardData,GlobalPathModelResult,GlobalVideoAnalysisResult,GlobalVideoAnalysisStatus,GroundTruthAnnotation,GroundTruthPolygon,GroundTruthStatus,GroundTruthSummary,LabelingVideoManifest,Mission,PathModelResult,PathPrediction,PathTrainingJob,Point,Reconstruction,Segmentation,TerrainMask,VideoInput} from './types'
export type Survey={name:string;start:Point;end:Point;route:Point[];movement_start?:string;movement_end?:string;pauses:{start_seconds:number;end_seconds:number;note:string}[];notes:string}
export function uploadMission(survey:Survey,videos:VideoInput[],onProgress:(value:number)=>void):Promise<Mission>{
  return new Promise((resolve,reject)=>{
    const data=new FormData(); data.append('survey',JSON.stringify(survey)); data.append('video_metadata',JSON.stringify(videos.map(({direction,orientation})=>({direction,orientation})))); videos.forEach(v=>data.append('videos',v.file))
    const xhr=new XMLHttpRequest(); xhr.open('POST','/api/v1/missions'); xhr.upload.onprogress=e=>e.lengthComputable&&onProgress(Math.round(e.loaded/e.total*100));
    xhr.onload=()=>{let body:any={};try{body=JSON.parse(xhr.responseText)}catch{} xhr.status===201?resolve(body):reject(new Error(body.detail||'Upload fehlgeschlagen'))}; xhr.onerror=()=>reject(new Error('Server nicht erreichbar. Die Mission wurde nicht verändert.')); xhr.send(data)
  })
}
export async function listMissions():Promise<Mission[]>{const r=await fetch('/api/v1/missions');if(!r.ok)throw new Error('Missionen konnten nicht geladen werden');return r.json()}
export async function getAnalysis(id:string):Promise<Analysis>{const r=await fetch(`/api/v1/missions/${id}/analysis`);if(!r.ok)throw new Error(r.status===404?'Für diese Mission liegt noch keine Auswertung vor.':'Auswertung konnte nicht geladen werden');return r.json()}
export async function getReconstruction(id:string):Promise<Reconstruction>{const r=await fetch(`/api/v1/missions/${id}/reconstruction`);if(!r.ok)throw new Error(r.status===404?'Für diese Mission liegt noch keine videobasierte Route vor.':'Rekonstruktion konnte nicht geladen werden');return r.json()}
export async function getSegmentation(id:string):Promise<Segmentation>{const r=await fetch(`/api/v1/missions/${id}/segmentation`);if(!r.ok)throw new Error(r.status===404?'Für diese Mission liegt noch keine Goal-4-Analyse vor.':'Goal-4-Analyse konnte nicht geladen werden');return r.json()}
export async function listGroundTruth(missionId:string,videoId?:string,includeGeometry=false):Promise<GroundTruthSummary>{const params=new URLSearchParams();if(videoId)params.set('video_id',videoId);if(includeGeometry)params.set('include_geometry','true');const query=params.size?`?${params}`:'';const r=await fetch(`/api/v1/missions/${missionId}/ground-truth${query}`);if(!r.ok)throw new Error('Ground-Truth-Übersicht konnte nicht geladen werden');return r.json()}
export async function getGroundTruth(missionId:string,videoId:string,frameIndex:number):Promise<GroundTruthAnnotation|null>{const r=await fetch(`/api/v1/missions/${missionId}/ground-truth/${videoId}/${frameIndex}`);if(r.status===404)return null;if(!r.ok)throw new Error('Ground Truth konnte nicht geladen werden');return r.json()}
export async function saveGroundTruth(missionId:string,videoId:string,frameIndex:number,payload:{timestamp_ms:number;source_frame_hash?:string;mask?:TerrainMask;polygons?:GroundTruthPolygon[];status:GroundTruthStatus;annotator:string;notes:string}):Promise<GroundTruthAnnotation>{const r=await fetch(`/api/v1/missions/${missionId}/ground-truth/${videoId}/${frameIndex}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'Ground Truth konnte nicht gespeichert werden');return body}
export async function deleteGroundTruth(missionId:string,videoId:string,frameIndex:number):Promise<void>{const r=await fetch(`/api/v1/missions/${missionId}/ground-truth/${videoId}/${frameIndex}`,{method:'DELETE'});if(!r.ok&&r.status!==404)throw new Error('Ground Truth konnte nicht gelöscht werden')}
export async function getLabelingVideos(missionId:string):Promise<LabelingVideoManifest>{const r=await fetch(`/api/v1/missions/${missionId}/labeling/videos`);if(!r.ok)throw new Error('Videoframes konnten nicht für das Labeling vorbereitet werden');return r.json()}
export async function runSegmentation(missionId:string):Promise<Segmentation>{const r=await fetch(`/api/v1/missions/${missionId}/segmentation`,{method:'POST'});let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'Auswertung konnte nicht gestartet werden');return body}
export async function getPathModel(missionId:string):Promise<PathModelResult|null>{const r=await fetch(`/api/v1/missions/${missionId}/path-model`);if(r.status===404)return null;if(!r.ok)throw new Error('CPU-Wegmodell konnte nicht geladen werden');return r.json()}
export async function trainPathModel(missionId:string):Promise<PathModelResult>{const r=await fetch(`/api/v1/missions/${missionId}/path-model/train`,{method:'POST'});let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'CPU-Wegmodell konnte nicht trainiert werden');return body}
export async function predictPathFrame(missionId:string,videoId:string,frameIndex:number):Promise<PathPrediction>{const r=await fetch(`/api/v1/missions/${missionId}/path-model/predict/${videoId}/${frameIndex}`);let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'KI-Wegmaske konnte nicht berechnet werden');return body}
export async function savePathRefinement(missionId:string,videoId:string,frameIndex:number,payload:{x:number;y:number;expected_kind:'missed_label'|'invented_path';action:'accept_model'}):Promise<{id:string;refinement_count:number}>{const r=await fetch(`/api/v1/missions/${missionId}/path-model/refinements/${videoId}/${frameIndex}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'Refinement konnte nicht gespeichert werden');return body}
export async function startPathTrainingJob(missionId:string,profile:'quick'|'overnight',durationHours:number):Promise<PathTrainingJob>{const params=new URLSearchParams({profile,duration_hours:String(durationHours)});const r=await fetch(`/api/v1/missions/${missionId}/path-model/train-background?${params}`,{method:'POST'});let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'Hintergrundtraining konnte nicht gestartet werden');return body}
export async function getPathTrainingJob(missionId:string):Promise<PathTrainingJob|null>{const r=await fetch(`/api/v1/missions/${missionId}/path-model/train-background`);if(r.status===404)return null;if(!r.ok)throw new Error('Trainingsstatus konnte nicht geladen werden');return r.json()}
export async function getGlobalModelDashboard():Promise<GlobalModelDashboardData>{const r=await fetch('/api/v1/path-model/global/dashboard');if(!r.ok)throw new Error('Globales Modellzentrum konnte nicht geladen werden');return r.json()}
export async function trainGlobalPathModel():Promise<GlobalPathModelResult>{const r=await fetch('/api/v1/path-model/global/train',{method:'POST'});let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'Globales Wegmodell konnte nicht trainiert werden');return body}
export async function predictGlobalPathFrame(missionId:string,videoId:string,frameIndex:number):Promise<PathPrediction>{const r=await fetch(`/api/v1/path-model/global/predict/${missionId}/${videoId}/${frameIndex}`);let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'Globale Frameanalyse konnte nicht berechnet werden');return body}
export async function startGlobalVideoAnalysis(missionId:string,videoId:string):Promise<GlobalVideoAnalysisStatus>{const r=await fetch(`/api/v1/path-model/global/analyze-video/${missionId}/${videoId}`,{method:'POST'});let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'Globale Videoanalyse konnte nicht gestartet werden');return body}
export async function getGlobalVideoAnalysisStatus(missionId:string,videoId:string):Promise<GlobalVideoAnalysisStatus|null>{const r=await fetch(`/api/v1/path-model/global/analyze-video/${missionId}/${videoId}/status`);if(r.status===404)return null;if(!r.ok)throw new Error('Status der globalen Videoanalyse konnte nicht geladen werden');return r.json()}
export async function getGlobalVideoAnalysisResult(missionId:string,videoId:string):Promise<GlobalVideoAnalysisResult>{const r=await fetch(`/api/v1/path-model/global/analyze-video/${missionId}/${videoId}/result`);let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||'Ergebnis der globalen Videoanalyse ist noch nicht verfügbar');return body}
